export const theme = {
  light: {
    background: '#F8F8F9',
    surface: '#FFFFFF',
    surfaceSecondary: '#F2F2F4',
    text: '#0A0A0A',
    textSecondary: '#6E6E73',
    textMuted: '#A1A1A6',
    border: '#E5E5EA',
    accent: '#0A0A0A',
    accentText: '#FFFFFF',
    accentSoft: '#F2F2F4',
    danger: '#FF3B30',
    success: '#34C759',
    overlay: 'rgba(0,0,0,0.45)',
  },
  dark: {
    background: '#0C0C0C',
    surface: '#161616',
    surfaceSecondary: '#1F1F1F',
    text: '#F5F5F7',
    textSecondary: '#98989D',
    textMuted: '#636366',
    border: '#2C2C2E',
    accent: '#F5F5F7',
    accentText: '#0A0A0A',
    accentSoft: '#1F1F1F',
    danger: '#FF453A',
    success: '#30D158',
    overlay: 'rgba(0,0,0,0.55)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  typography: {
    title: {
      fontSize: 24,
      fontWeight: '600' as const,
      letterSpacing: -0.6,
      lineHeight: 30,
    },
    heading: {
      fontSize: 16,
      fontWeight: '600' as const,
      letterSpacing: -0.3,
      lineHeight: 21,
    },
    body: {
      fontSize: 15,
      fontWeight: '400' as const,
      letterSpacing: -0.15,
      lineHeight: 21,
    },
    caption: {
      fontSize: 12,
      fontWeight: '400' as const,
      letterSpacing: 0,
      lineHeight: 16,
    },
    label: {
      fontSize: 11,
      fontWeight: '500' as const,
      letterSpacing: 0.8,
      lineHeight: 14,
      textTransform: 'uppercase' as const,
    },
    button: {
      fontSize: 14,
      fontWeight: '500' as const,
      letterSpacing: -0.1,
      lineHeight: 18,
    },
    buttonSm: {
      fontSize: 13,
      fontWeight: '500' as const,
      letterSpacing: -0.05,
      lineHeight: 16,
    },
  },
};

export type ThemeColors = typeof theme.light;
